In [2]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)
print(arr1.ndim)

[1 2 3]
1


In [3]:
arr2=np.arange(1,10,2)
print(arr2.shape)
arr2.reshape(5,1)

(5,)


array([[1],
       [3],
       [5],
       [7],
       [9]])

In [4]:
#np.ones(shape, dtype, order)
np.ones((3,4))
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
arrA=np.array([1,2,3,4,5])
arrB=np.array([5,6,7,8,9])

print(arrA+arrB)
print(arrB-arrA)
print(arrA*arrB)

[ 6  8 10 12 14]
[4 4 4 4 4]
[ 5 12 21 32 45]


In [6]:
# Joining 2 arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arrA = np.concatenate((arr1, arr2))

print(arrA)

# Joining 2 arrays along row and columns

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arrB = np.concatenate((arr1, arr2), axis=1)

arrC = np.concatenate((arr1, arr2), axis=0)

print(arrB)
print(arrC)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
# Split the array in 4 parts:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

arr2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr2 = np.array_split(arr2, 3, axis=1)

print(newarr)

print(newarr2)

## We can also use (hsplit), works as hstack

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


In [8]:
## Universal functions ##
arr1=np.array([1,2,3,4,5])
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [9]:
## Array slicing and indexing ## 
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)

print(arr[0])
print(arr[0][0])
print(arr[0:])
print(arr[1:,2:])


[1 2 3 4 5]
[1 2 3 4]
1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]


In [10]:
## Statical concept ##
data = np.array([1,2,3,4,5])

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))

3.0
3.0
1.4142135623730951
2.0


In [11]:
## Array search
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0) # Find the indexes where the values are even

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [12]:
## Array sort

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

# Note: This method returns a copy of the array, leaving the original array unchanged.
print(arr)


[0 1 2 3]
[3 2 0 1]


In [13]:
## Logical Operations ##

data= np.array([1,2,3,4,5,6,7,8,9,10])

print(data%2==0)

[False  True False  True False  True False  True False  True]


In [14]:
#Array filter

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]
