In [13]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)
print(arr1.ndim)

[1 2 3]
1


In [12]:
arr2=np.arange(1,10,2)
print(arr2.shape)
arr2.reshape(5,1)

(5,)


array([[1],
       [3],
       [5],
       [7],
       [9]])

In [21]:
#np.ones(shape, dtype, order)
np.ones((3,4))
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
arrA=np.array([1,2,3,4,5])
arrB=np.array([5,6,7,8,9])

print(arrA+arrB)
print(arrB-arrA)
print(arrA*arrB)

[ 6  8 10 12 14]
[4 4 4 4 4]
[ 5 12 21 32 45]


[1.         1.41421356 1.73205081 2.         2.23606798]
[1.         1.41421356 1.73205081 2.         2.23606798]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [37]:
## Universal functions ##
arr1=np.array([1,2,3,4,5])
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [48]:
## Array slicing and indexing ## 
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)

print(arr[0])
print(arr[0][0])
print(arr[0:])
print(arr[1:,2:])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]


In [52]:
## Statical concept ##
data = np.array([1,2,3,4,5])

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))

3.0
3.0
1.4142135623730951
2.0


In [53]:
## Logical Operations ##

data= np.array([1,2,3,4,5,6,7,8,9,10])

print(data%2==0)

[False  True False  True False  True False  True False  True]


HEADING TO PANDAS

In [55]:
import pandas as pd
## Series ##

data= (1,2,3,4,5)
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [56]:
## Creating series from dictionary##

dict= {"a":1,"b":2,"c":3,"d":4}
series=pd.Series(dict)

In [57]:
## Customized Index ##
data=(10,20,30)
inya=(1,2,3)
pd.Series(data, index=inya)

1    10
2    20
3    30
dtype: int64

In [61]:
import pandas as pd
data = { 
    'name':['Shivam', 'Satyam', 'Sundram'],
    'age': [17, 18, 19],
    'city': ['Patna', 'Ara', 'Delhi']
}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df)

      name  age   city
0   Shivam   17  Patna
1   Satyam   18    Ara
2  Sundram   19  Delhi


In [65]:
print(df.head(1))
print(df.tail(2))

     name  age   city
0  Shivam   17  Patna
      name  age   city
1   Satyam   18    Ara
2  Sundram   19  Delhi


In [72]:
## Acessing Data from DataFrame ##
nm=df['name']
print(nm)
## Here we picked 1 column so it became a series ##
print(type(nm))

# Row Wise #
print(df.loc[0])
# Index Location #
print(df.iloc[0])
print(df.iloc[0][0])

# Acessing a specified element #
print(df.at[1,"age"])
print(df.iat[2,2])

0     Shivam
1     Satyam
2    Sundram
Name: name, dtype: object
<class 'pandas.core.series.Series'>
name    Shivam
age         17
city     Patna
Name: 0, dtype: object
name    Shivam
age         17
city     Patna
Name: 0, dtype: object
Shivam
18
Delhi


C:\Users\SANTOSH\AppData\Local\Temp\ipykernel_7776\3214708242.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[0][0])


In [ ]:
## Data Manipulation ##

# Adding a column #
df["salery"]=[50000,60000,70000]

# Removing a column #
df.drop('salery',axis=1, inplace=True)

In [80]:
# Statical Summery #
df.describe()

age
count   3.0
mean   18.0
std     1.0
min    17.0
25%    17.5
50%    18.0
75%    18.5
max    19.0

In [105]:
## Data Analysis with Pandas ##

import pandas as pd
df= pd.read_csv("username-password-recovery-code.csv")

print(df.head(3))
print(df.describe())


  Username; Identifier;One-time password;Recovery code;First name;Last name;Department;Location
0  booker12;9012;12se74;rb9012;Rachel;Booker;Sale...                                           
1  grey07;2070;04ap67;lg2070;Laura;Grey;Depot;London                                           
2  johnson81;4081;30no86;cj4081;Craig;Johnson;Dep...                                           
       Username; Identifier;One-time password;Recovery code;First name;Last name;Department;Location
count                                                   5                                           
unique                                                  5                                           
top     booker12;9012;12se74;rb9012;Rachel;Booker;Sale...                                           
freq                                                    1                                           


In [ ]:
## Handeling missing values ##
df.isnull()
df.isnull().any(axis=1)
df.isnull().sum()
df.fillna(0)
df['Identifier_fillNA']=df['Identifier'].fillna(df['Identifier'].mean())


Username; Identifier;One-time password;Recovery code;First name;Last name;Department;Location
0  booker12;9012;12se74;rb9012;Rachel;Booker;Sale...                                           
1  grey07;2070;04ap67;lg2070;Laura;Grey;Depot;London                                           
2  johnson81;4081;30no86;cj4081;Craig;Johnson;Dep...                                           
3  jenkins46;9346;14ju73;mj9346;Mary;Jenkins;Engi...                                           
4  smith79;5079;09ja61;js5079;Jamie;Smith;Enginee...

In [ ]:
## Renaming Columns ##
df.rename(column={"Username":"Name"})
## Change Datatype ##
df['value_new']=df['value'].astype(float)
## Define new functions in values ##
df['new_value']=df['value'].apply(lambda x:x**2)

In [ ]:
## Data aggregation and grouping ##
import pandas as pd

df1 = {
    'key': ['A', 'B', 'C'],
    'value': [1, 2, 3]
}

df2 = {
    'key': ['A', 'B', 'D'],
    'value': [4, 5, 6]
}

df1 = pd.DataFrame(df1)
df2 = pd.DataFrame(df2)

pd.merge(df1,df2,on='key',how='inner')

pd.merge(df1,df2,on='key',how='outer')

pd.merge(df1,df2,on='key',how='left')

pd.merge(df1,df2,on='key',how='right')


key  value_x  value_y
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [ ]:
## Reading data from different sources ##
import pandas as pd
from io import StringIO
data={}
df=pd.read_json(StringIO(data))
df.to_json(orient='record')    ## By Default orient = index ##


df=pd.read_csv('http...............',header=None)
df.head()
df.to_csv('vine.csv')   ## new file to save ##

pd.read_hrml('url',match='country',header=0)
